### ISSUE TITLE
Issues with Running coord_conversion.R and download_movebank.py Scripts

### ISSUE THREAD

**Issue by qiaozhijian** [Mesoptier/trajectory-clustering#6]
Hello Sir,

I hope this message finds you well. I am writing to report a couple of issues I encountered while working with the dataset in your GitHub repository.

1. **Missing File Error in `coord_conversion.R`**:
   When I attempt to run the `./coord_conversion.R` script, I encounter an error due to a missing file. The error message is as follows:
```
cannot open file 'Data_for_Mann_et_al_RSBL/Bladon & Church route recapping/bladon heath/a55/dataset.txt': No such file or directory
```
It appears that the `dataset.txt` file is either missing from the repository or the path is incorrect. Could you kindly check if the file is supposed to be included in the repository, or if the path specified in the script needs to be updated?

2. **Broken Download Link in `download_movebank.py`**:
Additionally, the download link provided in the `./download_movebank.py` script seems to be invalid or has expired. When I try to use the script to download the data, it fails due to the broken link.

Would it be possible for you to look into these issues? If it's not too much trouble, could you also provide the dataset directly to my email address at zqiaoac@connect.ust.hk? This would be immensely helpful for my ongoing research.

I want to take a moment to thank you for your work and for sharing the resources on GitHub. Your contribution is greatly appreciated by the community, and I look forward to your response.

Best regards,
George

**Comment by kbuchin** [comment]
Data sets:
- pigeons: https://royalsocietypublishing.org/action/downloadSupplement?doi=10.1098%2Frsbl.2013.0885&file=rsbl-2013-0885-file006.gz
- movebank: you can also download it from the page of the corresponding study: https://www.movebank.org/cms/webapp?gwt_fragment=page%3Dstudies%2Cpath%3Dstudy560041066

Concerning the first error message: At least I get an error already when using get (essentially this problem here: https://github.com/langchain-ai/langchain/issues/11590) But the larger issue would come later, namely that rgdal was discontinued, so we will need to use an alternative

But you were mostly looking for the data? Then with the above links, you should have all you need.

**Comment by qiaozhijian** [comment]
Dear Professor Buchin,

Your provided links for the pigeon and movebank datasets are available.

Regarding the `rgdal` package, I have successfully managed to manually install the library on my system and resolve the reported errors. I appreciate your concern.
